Update 4-connectors.md
Add package version to prevent error, as old syntax is no longer supported in the updated package.
`UnhandledPromiseRejectionWarning: TypeError: db.collection is not a function`